name: C/C++ CI

on:
  push:
    branches:
      - '*'

env:
  isNightly: ${{ contains(github.ref, 'dev') }}
  isFinalRelease: ${{ contains(github.ref, 'master') }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Get uClibc toolchain
      uses: i3h/download-release-asset@v1
      with:
        owner: telmomarques
        repo: uClibc-toolchain
        tag: latest
        file: toolchain.tar

    - name: Install uClibc ARM cross compiler
      run: tar -xf toolchain.tar

    - name: Compile
      run: rm -rf compile && package/compile uclibc

    - name: Copy uClibc executables
      run: mkdir -p dist && cp compile/{runit,runsv,runsvchdir,runsvdir,sv,svlogd,choose,chpst,load,runit-init,utmpset} dist

    - name: Package binaries
      run: cd dist && tar -cvf runit.tar *

    - name: Release Candidate
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isNightly == 'true'
      with:
        automatic_release_tag: latest-rc
        files: dist/runit.tar
        prerelease: true
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: latest-rc

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isFinalRelease == 'true'
      with:
        automatic_release_tag: latest-rc
        files: dist/runit.tar
        prerelease: false
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: stable